services:
  mysql_simple_manage_products:
    image: mysql:8.0.30
    container_name: mysql_simple_manage_products
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      - simple_manage_products_network
    volumes:
      - mysql_simple_manage_products:/var/lib/mysql
    env_file:
      - .env
    environment:
       MYSQL_ROOT_PASSWORD : ROOT
       MYSQL_PASSWORD : SECRET
       MYSQL_USER : ADMIN
       MYSQL_DATABASE : simple_manage_products
  
  redis_simple_manage_products:
    image: redis:alpine3.16
    container_name: redis_simple_manage_products
    command: redis-server --save 60 1 --loglevel warning --requirepass 1234
    ports:
      - '6379:6379'
    networks:
      - simple_manage_products_network
    volumes:
      - redis_simple_manage_products:/data
      - ./redis.conf:/etc/redis/redis.conf

volumes:
  mysql_simple_manage_products: {}
  redis_simple_manage_products: {}

networks:
  simple_manage_products_network: {}
  